#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : gnocchiclient
Version  : 2.2.0
Release  : 11
URL      : http://tarballs.openstack.org/python-gnocchiclient/gnocchiclient-2.2.0.tar.gz
Source0  : http://tarballs.openstack.org/python-gnocchiclient/gnocchiclient-2.2.0.tar.gz
Summary  : Python client library for Gnocchi
Group    : Development/Tools
License  : Apache-2.0
Requires: gnocchiclient-bin
Requires: gnocchiclient-python
Requires: Sphinx
Requires: cliff
Requires: coverage
Requires: futurist
Requires: keystoneauth1
Requires: oslo.serialization
Requires: oslo.utils
Requires: oslosphinx
Requires: oslotest
Requires: pbr
Requires: python-subunit
Requires: six
Requires: tempest-lib
Requires: testrepository
Requires: testtools
BuildRequires : configparser-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools

%description
=============
gnocchiclient
=============
Python bindings to the OpenStack Gnocchi API

%package bin
Summary: bin components for the gnocchiclient package.
Group: Binaries

%description bin
bin components for the gnocchiclient package.


%package python
Summary: python components for the gnocchiclient package.
Group: Default

%description python
python components for the gnocchiclient package.


%prep
%setup -q -n gnocchiclient-2.2.0

%build
export LANG=C
export SOURCE_DATE_EPOCH=1489331986
python2 setup.py build -b py2
python3 setup.py build -b py3

%install
export SOURCE_DATE_EPOCH=1489331986
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot} --force
python3 -tt setup.py build -b py3 install --root=%{buildroot} --force

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/gnocchi

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
